ALTER TABLE tasks
ADD COLUMN sub_title VARCHAR(255) NULL,
ADD COLUMN description TEXT NULL,
ADD COLUMN due_date BIGINT NULL,
ADD COLUMN updated_at BIGINT DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)::BIGINT;
