/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Go Vanilla Task Manager API
 * RESTful API for task management built with vanilla Go.
 *
 * ## Timezone Support
 * All timestamps are stored and returned as epoch milliseconds (Unix time in milliseconds).
 * The API includes timezone information in responses based on user preferences.
 *
 * - All timestamp fields use `int64` format (epoch milliseconds)
 * - Responses include `timezone` field indicating the user's timezone preference
 * - Users can set their timezone preference via `PUT /auth/timezone`
 * - Default timezone is UTC if not specified
 *
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker'

export const getGetHealthResponseMock = (): string => faker.word.sample()

export const getPostAuthRegisterResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostAuthLoginResponseMock = (
	overrideResponse: Partial<Extract<LoginResponse, object>> = {}
): LoginResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			token: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			user: faker.helpers.arrayElement([
				{
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					name: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
					timezone: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				},
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostAuthLogoutResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetAuthMeResponseMock = (
	overrideResponse: Partial<Extract<UserResponse, object>> = {}
): UserResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
			timezone: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPutAuthTimezoneResponseMock = (
	overrideResponse: Partial<Extract<UserResponse, object>> = {}
): UserResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
			timezone: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTasksResponseMock = (
	overrideResponse: Partial<Extract<TasksListResponse, object>> = {}
): TasksListResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			data: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					category_id: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					title: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					sub_title: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					description: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					due_date: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					priority: faker.helpers.arrayElement([
						faker.helpers.arrayElement(['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const),
						undefined,
					]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					deleted_at: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					progress_percentage: faker.helpers.arrayElement([faker.number.int(), undefined]),
					tags: faker.helpers.arrayElement([
						Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
							() => ({
								id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								color_hex: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
							})
						),
						undefined,
					]),
					subtasks: faker.helpers.arrayElement([
						Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
							() => ({
								id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								title: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
								created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
								updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
							})
						),
						undefined,
					]),
				})),
				undefined,
			]),
			meta: faker.helpers.arrayElement([
				{
					page: faker.helpers.arrayElement([faker.number.int(), undefined]),
					limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
					total_data: faker.helpers.arrayElement([faker.number.int(), undefined]),
					total_page: faker.helpers.arrayElement([faker.number.int(), undefined]),
					has_next: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					has_prev: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
				},
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostTasksResponseMock = (
	overrideResponse: Partial<Extract<TaskResponse, object>> = {}
): TaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			category_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			sub_title: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
				undefined,
			]),
			description: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
				undefined,
			]),
			completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			due_date: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			priority: faker.helpers.arrayElement([
				faker.helpers.arrayElement(['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			deleted_at: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			progress_percentage: faker.helpers.arrayElement([faker.number.int(), undefined]),
			tags: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					name: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					color_hex: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				})),
				undefined,
			]),
			subtasks: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					title: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				})),
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTasksIdResponseMock = (
	overrideResponse: Partial<Extract<TaskResponse, object>> = {}
): TaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			category_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			sub_title: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
				undefined,
			]),
			description: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
				undefined,
			]),
			completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			due_date: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			priority: faker.helpers.arrayElement([
				faker.helpers.arrayElement(['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			deleted_at: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			progress_percentage: faker.helpers.arrayElement([faker.number.int(), undefined]),
			tags: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					name: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					color_hex: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				})),
				undefined,
			]),
			subtasks: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					title: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				})),
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPutTasksIdResponseMock = (
	overrideResponse: Partial<Extract<TaskResponse, object>> = {}
): TaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			category_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			sub_title: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
				undefined,
			]),
			description: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]),
				undefined,
			]),
			completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			due_date: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			priority: faker.helpers.arrayElement([
				faker.helpers.arrayElement(['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			deleted_at: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			progress_percentage: faker.helpers.arrayElement([faker.number.int(), undefined]),
			tags: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					name: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					color_hex: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				})),
				undefined,
			]),
			subtasks: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					title: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
				})),
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getDeleteTasksIdResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPatchTasksIdCompleteResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPatchTasksIdUncompleteResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPatchTasksIdRestoreResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTasksAnalyticsSummaryResponseMock = (
	overrideResponse: Partial<Extract<AnalyticsResponse, object>> = {}
): AnalyticsResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			total_active: faker.helpers.arrayElement([faker.number.int(), undefined]),
			total_completed: faker.helpers.arrayElement([faker.number.int(), undefined]),
			total_overdue: faker.helpers.arrayElement([faker.number.int(), undefined]),
			completion_percentage: faker.helpers.arrayElement([
				faker.number.float({ fractionDigits: 2 }),
				undefined,
			]),
			priority_distribution: faker.helpers.arrayElement([
				{
					[faker.string.alphanumeric(5)]: faker.number.int(),
				},
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostTasksBulkDeleteResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostTasksBulkCompleteResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostTasksIdTagsResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTasksIdTagsResponseMock = (
	overrideResponse: Partial<Extract<TagsResponse, object>> = {}
): TagsResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		})),
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getDeleteTasksIdTagsTagIdResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetCategoriesResponseMock = (
	overrideResponse: Partial<Extract<CategoriesResponse, object>> = {}
): CategoriesResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		})),
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostCategoriesResponseMock = (
	overrideResponse: Partial<Extract<CategoryResponse, object>> = {}
): CategoryResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetCategoriesIdResponseMock = (
	overrideResponse: Partial<Extract<CategoryResponse, object>> = {}
): CategoryResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPutCategoriesIdResponseMock = (
	overrideResponse: Partial<Extract<CategoryResponse, object>> = {}
): CategoryResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getDeleteCategoriesIdResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTagsResponseMock = (
	overrideResponse: Partial<Extract<TagsResponse, object>> = {}
): TagsResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		})),
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostTagsResponseMock = (
	overrideResponse: Partial<Extract<TagResponse, object>> = {}
): TagResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTagsIdResponseMock = (
	overrideResponse: Partial<Extract<TagResponse, object>> = {}
): TagResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPutTagsIdResponseMock = (
	overrideResponse: Partial<Extract<TagResponse, object>> = {}
): TagResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			color_hex: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getDeleteTagsIdResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTagsIdTasksResponseMock = (
	overrideResponse: Partial<Extract<TasksListResponse, object>> = {}
): TasksListResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			data: faker.helpers.arrayElement([
				Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
					id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
					category_id: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					title: faker.helpers.arrayElement([
						faker.string.alpha({ length: { min: 10, max: 20 } }),
						undefined,
					]),
					sub_title: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					description: faker.helpers.arrayElement([
						faker.helpers.arrayElement([
							faker.string.alpha({ length: { min: 10, max: 20 } }),
							null,
						]),
						undefined,
					]),
					completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					due_date: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					priority: faker.helpers.arrayElement([
						faker.helpers.arrayElement(['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const),
						undefined,
					]),
					created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
					deleted_at: faker.helpers.arrayElement([
						faker.helpers.arrayElement([faker.number.int(), null]),
						undefined,
					]),
					progress_percentage: faker.helpers.arrayElement([faker.number.int(), undefined]),
					tags: faker.helpers.arrayElement([
						Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
							() => ({
								id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								name: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								color_hex: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
							})
						),
						undefined,
					]),
					subtasks: faker.helpers.arrayElement([
						Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
							() => ({
								id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
								title: faker.helpers.arrayElement([
									faker.string.alpha({ length: { min: 10, max: 20 } }),
									undefined,
								]),
								is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
								created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
								updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
							})
						),
						undefined,
					]),
				})),
				undefined,
			]),
			meta: faker.helpers.arrayElement([
				{
					page: faker.helpers.arrayElement([faker.number.int(), undefined]),
					limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
					total_data: faker.helpers.arrayElement([faker.number.int(), undefined]),
					total_page: faker.helpers.arrayElement([faker.number.int(), undefined]),
					has_next: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
					has_prev: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
				},
				undefined,
			]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPostTasksIdSubtasksResponseMock = (
	overrideResponse: Partial<Extract<SubtaskResponse, object>> = {}
): SubtaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTasksIdSubtasksResponseMock = (
	overrideResponse: Partial<Extract<SubtasksResponse, object>> = {}
): SubtasksResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		})),
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetSubtasksIdResponseMock = (
	overrideResponse: Partial<Extract<SubtaskResponse, object>> = {}
): SubtaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPutSubtasksIdResponseMock = (
	overrideResponse: Partial<Extract<SubtaskResponse, object>> = {}
): SubtaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getDeleteSubtasksIdResponseMock = (
	overrideResponse: Partial<Extract<SuccessResponse, object>> = {}
): SuccessResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([faker.helpers.arrayElement([{}, null]), undefined]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getPatchSubtasksIdToggleResponseMock = (
	overrideResponse: Partial<Extract<SubtaskResponse, object>> = {}
): SubtaskResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			title: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			is_completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
			updated_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetActivityLogsResponseMock = (
	overrideResponse: Partial<Extract<ActivityLogsResponse, object>> = {}
): ActivityLogsResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			action: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			entity_type: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			entity_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			details: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			ip_address: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			user_agent: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		})),
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetActivityLogsIdResponseMock = (
	overrideResponse: Partial<Extract<ActivityLogResponse, object>> = {}
): ActivityLogResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			action: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			entity_type: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			entity_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			details: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			ip_address: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			user_agent: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		},
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})

export const getGetTasksIdActivityLogsResponseMock = (
	overrideResponse: Partial<Extract<ActivityLogsResponse, object>> = {}
): ActivityLogsResponse => ({
	status: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	message: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	data: faker.helpers.arrayElement([
		Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			user_id: faker.helpers.arrayElement([faker.number.int(), undefined]),
			task_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			action: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			entity_type: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			entity_id: faker.helpers.arrayElement([
				faker.helpers.arrayElement([faker.number.int(), null]),
				undefined,
			]),
			details: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			ip_address: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			user_agent: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([faker.number.int(), undefined]),
		})),
		undefined,
	]),
	timezone: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
})
