// @ts-nocheck
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Go Vanilla Task Manager API
 * RESTful API for task management built with vanilla Go.
 *
 * ## Timezone Support
 * All timestamps are stored and returned as epoch milliseconds (Unix time in milliseconds).
 * The API includes timezone information in responses based on user preferences.
 *
 * - All timestamp fields use `int64` format (epoch milliseconds)
 * - Responses include `timezone` field indicating the user's timezone preference
 * - Users can set their timezone preference via `PUT /auth/timezone`
 * - Default timezone is UTC if not specified
 *
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * @nullable
 */
export type SuccessResponseData = { [key: string]: unknown } | null;

export interface SuccessResponse {
  status?: string;
  message?: string;
  /** @nullable */
  data?: SuccessResponseData;
  /** User timezone used for response formatting */
  timezone?: string;
}

/**
 * @nullable
 */
export type ErrorResponseData = { [key: string]: unknown } | null;

export interface ErrorResponse {
  status?: string;
  message?: string;
  /** @nullable */
  data?: ErrorResponseData;
}

export interface User {
  id?: number;
  name?: string;
  email?: string;
  /** User timezone preference */
  timezone?: string;
  /** Epoch milliseconds */
  created_at?: number;
  /** Epoch milliseconds */
  updated_at?: number;
}

export type LoginResponseData = {
  token?: string;
  user?: User;
};

export interface LoginResponse {
  status?: string;
  message?: string;
  data?: LoginResponseData;
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface UserResponse {
  status?: string;
  message?: string;
  data?: User;
  /** User timezone used for response formatting */
  timezone?: string;
}

export type TaskPriority = typeof TaskPriority[keyof typeof TaskPriority];


export const TaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export interface Tag {
  id?: number;
  user_id?: number;
  name?: string;
  color_hex?: string;
  /** Epoch milliseconds */
  created_at?: number;
}

export interface Subtask {
  id?: number;
  task_id?: number;
  title?: string;
  is_completed?: boolean;
  /** Epoch milliseconds */
  created_at?: number;
  /** Epoch milliseconds */
  updated_at?: number;
}

export interface Task {
  id?: number;
  user_id?: number;
  /** @nullable */
  category_id?: number | null;
  title?: string;
  /** @nullable */
  sub_title?: string | null;
  /** @nullable */
  description?: string | null;
  completed?: boolean;
  /**
     * Epoch milliseconds
     * @nullable
     */
  due_date?: number | null;
  priority?: TaskPriority;
  /** Epoch milliseconds */
  created_at?: number;
  /** Epoch milliseconds */
  updated_at?: number;
  /**
     * Epoch milliseconds
     * @nullable
     */
  deleted_at?: number | null;
  progress_percentage?: number;
  tags?: Tag[];
  subtasks?: Subtask[];
}

export type TaskCreatePriority = typeof TaskCreatePriority[keyof typeof TaskCreatePriority];


export const TaskCreatePriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export interface TaskCreate {
  title: string;
  /** @nullable */
  sub_title?: string | null;
  /** @nullable */
  description?: string | null;
  /**
     * Epoch milliseconds
     * @nullable
     */
  due_date?: number | null;
  priority?: TaskCreatePriority;
  /** @nullable */
  category_id?: number | null;
}

export type TaskUpdatePriority = typeof TaskUpdatePriority[keyof typeof TaskUpdatePriority];


export const TaskUpdatePriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export interface TaskUpdate {
  title?: string;
  /** @nullable */
  sub_title?: string | null;
  /** @nullable */
  description?: string | null;
  /**
     * Epoch milliseconds
     * @nullable
     */
  due_date?: number | null;
  priority?: TaskUpdatePriority;
  /** @nullable */
  category_id?: number | null;
  completed?: boolean;
}

export interface TaskResponse {
  status?: string;
  message?: string;
  data?: Task;
  /** User timezone used for response formatting */
  timezone?: string;
}

export type TasksListResponseDataMeta = {
  page?: number;
  limit?: number;
  total_data?: number;
  total_page?: number;
  has_next?: boolean;
  has_prev?: boolean;
};

export type TasksListResponseData = {
  data?: Task[];
  meta?: TasksListResponseDataMeta;
};

export interface TasksListResponse {
  status?: string;
  message?: string;
  data?: TasksListResponseData;
  /** User timezone used for response formatting */
  timezone?: string;
}

export type AnalyticsResponseDataPriorityDistribution = {[key: string]: number};

export type AnalyticsResponseData = {
  total_active?: number;
  total_completed?: number;
  total_overdue?: number;
  completion_percentage?: number;
  priority_distribution?: AnalyticsResponseDataPriorityDistribution;
};

export interface AnalyticsResponse {
  status?: string;
  message?: string;
  data?: AnalyticsResponseData;
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface Category {
  id?: number;
  user_id?: number;
  name?: string;
  color_hex?: string;
  /** Epoch milliseconds */
  created_at?: number;
}

export interface CategoryCreate {
  name: string;
  color_hex?: string;
}

export interface CategoryUpdate {
  name?: string;
  color_hex?: string;
}

export interface CategoryResponse {
  status?: string;
  message?: string;
  data?: Category;
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface CategoriesResponse {
  status?: string;
  message?: string;
  data?: Category[];
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface TagCreate {
  name: string;
  color_hex?: string;
}

export interface TagUpdate {
  name?: string;
  color_hex?: string;
}

export interface TagResponse {
  status?: string;
  message?: string;
  data?: Tag;
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface TagsResponse {
  status?: string;
  message?: string;
  data?: Tag[];
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface SubtaskCreate {
  title: string;
}

export interface SubtaskUpdate {
  title?: string;
  is_completed?: boolean;
}

export interface SubtaskResponse {
  status?: string;
  message?: string;
  data?: Subtask;
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface SubtasksResponse {
  status?: string;
  message?: string;
  data?: Subtask[];
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface ActivityLog {
  id?: number;
  user_id?: number;
  /** @nullable */
  task_id?: number | null;
  action?: string;
  entity_type?: string;
  /** @nullable */
  entity_id?: number | null;
  details?: string;
  ip_address?: string;
  user_agent?: string;
  /** Epoch milliseconds */
  created_at?: number;
}

export interface ActivityLogResponse {
  status?: string;
  message?: string;
  data?: ActivityLog;
  /** User timezone used for response formatting */
  timezone?: string;
}

export interface ActivityLogsResponse {
  status?: string;
  message?: string;
  data?: ActivityLog[];
  /** User timezone used for response formatting */
  timezone?: string;
}

export type PostAuthRegisterBody = {
  name: string;
  email: string;
  password: string;
  /** User timezone (defaults to UTC if not provided) */
  timezone?: string;
};

export type PostAuthLoginBody = {
  email: string;
  password: string;
};

export type PutAuthTimezoneBody = {
  /** Valid IANA timezone identifier */
  timezone: string;
};

export type GetTasksParams = {
page?: number;
limit?: number;
completed?: boolean;
search?: string;
priority?: GetTasksPriority;
category_id?: number;
sort_by?: GetTasksSortBy;
sort_order?: GetTasksSortOrder;
};

export type GetTasksPriority = typeof GetTasksPriority[keyof typeof GetTasksPriority];


export const GetTasksPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export type GetTasksSortBy = typeof GetTasksSortBy[keyof typeof GetTasksSortBy];


export const GetTasksSortBy = {
  created_at: 'created_at',
  updated_at: 'updated_at',
  due_date: 'due_date',
  priority: 'priority',
  title: 'title',
} as const;

export type GetTasksSortOrder = typeof GetTasksSortOrder[keyof typeof GetTasksSortOrder];


export const GetTasksSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;

export type PostTasksBulkDeleteBody = {
  /** @maxItems 100 */
  task_ids: number[];
};

export type PostTasksBulkCompleteBody = {
  /** @maxItems 100 */
  task_ids: number[];
};

export type PostTasksIdTagsBody = {
  tag_id: number;
};

export type GetActivityLogsParams = {
page?: number;
limit?: number;
};

/**
 * Returns API status
 * @summary Health check endpoint
 */
export const getHealth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axios.get(
      `/health`,{
        responseType: 'text',
    ...options,}
    );
  }
export const getGetHealthUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/health`,
    baseURL: '',


  });
}

/**
 * Create a new user account
 * @summary Register a new user
 */
export const postAuthRegister = (
    postAuthRegisterBody: PostAuthRegisterBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.post(
      `/auth/register`,
      postAuthRegisterBody,options
    );
  }
export const getPostAuthRegisterUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/auth/register`,
    baseURL: '',


  });
}

/**
 * Authenticate user and return JWT token
 * @summary Login user
 */
export const postAuthLogin = (
    postAuthLoginBody: PostAuthLoginBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponse>> => {
    return axios.post(
      `/auth/login`,
      postAuthLoginBody,options
    );
  }
export const getPostAuthLoginUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/auth/login`,
    baseURL: '',


  });
}

/**
 * Invalidate current session
 * @summary Logout user
 */
export const postAuthLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.post(
      `/auth/logout`,
      undefined,options
    );
  }
export const getPostAuthLogoutUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/auth/logout`,
    baseURL: '',


  });
}

/**
 * Get information about the authenticated user
 * @summary Get current user
 */
export const getAuthMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axios.get(
      `/auth/me`,options
    );
  }
export const getGetAuthMeUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/auth/me`,
    baseURL: '',


  });
}

/**
 * Update the timezone preference for the authenticated user
 * @summary Update user timezone
 */
export const putAuthTimezone = (
    putAuthTimezoneBody: PutAuthTimezoneBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    return axios.put(
      `/auth/timezone`,
      putAuthTimezoneBody,options
    );
  }
export const getPutAuthTimezoneUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/auth/timezone`,
    baseURL: '',


  });
}

/**
 * Retrieve paginated list of tasks for authenticated user
 * @summary Get all tasks
 */
export const getTasks = (
    params?: GetTasksParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TasksListResponse>> => {
    return axios.get(
      `/tasks`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getGetTasksUrl = (params?: GetTasksParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks`,
    baseURL: '',
    params,

  });
}

/**
 * Create a new task for the authenticated user
 * @summary Create a new task
 */
export const postTasks = (
    taskCreate: TaskCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaskResponse>> => {
    return axios.post(
      `/tasks`,
      taskCreate,options
    );
  }
export const getPostTasksUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks`,
    baseURL: '',


  });
}

/**
 * Retrieve a specific task by ID
 * @summary Get task by ID
 */
export const getTasksId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaskResponse>> => {
    return axios.get(
      `/tasks/${id}`,options
    );
  }
export const getGetTasksIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}`,
    baseURL: '',


  });
}

/**
 * Update an existing task
 * @summary Update task
 */
export const putTasksId = (
    id: number,
    taskUpdate: TaskUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TaskResponse>> => {
    return axios.put(
      `/tasks/${id}`,
      taskUpdate,options
    );
  }
export const getPutTasksIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}`,
    baseURL: '',


  });
}

/**
 * Soft delete a task
 * @summary Delete task
 */
export const deleteTasksId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.delete(
      `/tasks/${id}`,options
    );
  }
export const getDeleteTasksIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}`,
    baseURL: '',


  });
}

/**
 * Mark a task as completed
 * @summary Mark task as completed
 */
export const patchTasksIdComplete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.patch(
      `/tasks/${id}/complete`,
      undefined,options
    );
  }
export const getPatchTasksIdCompleteUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/complete`,
    baseURL: '',


  });
}

/**
 * Mark a task as uncompleted
 * @summary Mark task as uncompleted
 */
export const patchTasksIdUncomplete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.patch(
      `/tasks/${id}/uncomplete`,
      undefined,options
    );
  }
export const getPatchTasksIdUncompleteUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/uncomplete`,
    baseURL: '',


  });
}

/**
 * Restore a soft-deleted task
 * @summary Restore deleted task
 */
export const patchTasksIdRestore = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.patch(
      `/tasks/${id}/restore`,
      undefined,options
    );
  }
export const getPatchTasksIdRestoreUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/restore`,
    baseURL: '',


  });
}

/**
 * Get statistics and summary of tasks
 * @summary Get task analytics summary
 */
export const getTasksAnalyticsSummary = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AnalyticsResponse>> => {
    return axios.get(
      `/tasks/analytics/summary`,options
    );
  }
export const getGetTasksAnalyticsSummaryUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/analytics/summary`,
    baseURL: '',


  });
}

/**
 * Delete multiple tasks at once
 * @summary Bulk delete tasks
 */
export const postTasksBulkDelete = (
    postTasksBulkDeleteBody: PostTasksBulkDeleteBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.post(
      `/tasks/bulk-delete`,
      postTasksBulkDeleteBody,options
    );
  }
export const getPostTasksBulkDeleteUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/bulk-delete`,
    baseURL: '',


  });
}

/**
 * Mark multiple tasks as completed at once
 * @summary Bulk complete tasks
 */
export const postTasksBulkComplete = (
    postTasksBulkCompleteBody: PostTasksBulkCompleteBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.post(
      `/tasks/bulk-complete`,
      postTasksBulkCompleteBody,options
    );
  }
export const getPostTasksBulkCompleteUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/bulk-complete`,
    baseURL: '',


  });
}

/**
 * Associate a tag with a task
 * @summary Add tag to task
 */
export const postTasksIdTags = (
    id: number,
    postTasksIdTagsBody: PostTasksIdTagsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.post(
      `/tasks/${id}/tags`,
      postTasksIdTagsBody,options
    );
  }
export const getPostTasksIdTagsUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/tags`,
    baseURL: '',


  });
}

/**
 * Get all tags associated with a task
 * @summary Get task tags
 */
export const getTasksIdTags = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagsResponse>> => {
    return axios.get(
      `/tasks/${id}/tags`,options
    );
  }
export const getGetTasksIdTagsUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/tags`,
    baseURL: '',


  });
}

/**
 * Remove a tag association from a task
 * @summary Remove tag from task
 */
export const deleteTasksIdTagsTagId = (
    id: number,
    tagId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.delete(
      `/tasks/${id}/tags/${tagId}`,options
    );
  }
export const getDeleteTasksIdTagsTagIdUrl = (id: number,
    tagId: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/tags/${tagId}`,
    baseURL: '',


  });
}

/**
 * Retrieve all categories for authenticated user
 * @summary Get all categories
 */
export const getCategories = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoriesResponse>> => {
    return axios.get(
      `/categories`,options
    );
  }
export const getGetCategoriesUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/categories`,
    baseURL: '',


  });
}

/**
 * Create a new category
 * @summary Create category
 */
export const postCategories = (
    categoryCreate: CategoryCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryResponse>> => {
    return axios.post(
      `/categories`,
      categoryCreate,options
    );
  }
export const getPostCategoriesUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/categories`,
    baseURL: '',


  });
}

/**
 * Retrieve a specific category
 * @summary Get category by ID
 */
export const getCategoriesId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryResponse>> => {
    return axios.get(
      `/categories/${id}`,options
    );
  }
export const getGetCategoriesIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/categories/${id}`,
    baseURL: '',


  });
}

/**
 * Update an existing category
 * @summary Update category
 */
export const putCategoriesId = (
    id: number,
    categoryUpdate: CategoryUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CategoryResponse>> => {
    return axios.put(
      `/categories/${id}`,
      categoryUpdate,options
    );
  }
export const getPutCategoriesIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/categories/${id}`,
    baseURL: '',


  });
}

/**
 * Delete a category
 * @summary Delete category
 */
export const deleteCategoriesId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.delete(
      `/categories/${id}`,options
    );
  }
export const getDeleteCategoriesIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/categories/${id}`,
    baseURL: '',


  });
}

/**
 * Retrieve all tags for authenticated user
 * @summary Get all tags
 */
export const getTags = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagsResponse>> => {
    return axios.get(
      `/tags`,options
    );
  }
export const getGetTagsUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tags`,
    baseURL: '',


  });
}

/**
 * Create a new tag
 * @summary Create tag
 */
export const postTags = (
    tagCreate: TagCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagResponse>> => {
    return axios.post(
      `/tags`,
      tagCreate,options
    );
  }
export const getPostTagsUrl = () => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tags`,
    baseURL: '',


  });
}

/**
 * Retrieve a specific tag
 * @summary Get tag by ID
 */
export const getTagsId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagResponse>> => {
    return axios.get(
      `/tags/${id}`,options
    );
  }
export const getGetTagsIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tags/${id}`,
    baseURL: '',


  });
}

/**
 * Update an existing tag
 * @summary Update tag
 */
export const putTagsId = (
    id: number,
    tagUpdate: TagUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TagResponse>> => {
    return axios.put(
      `/tags/${id}`,
      tagUpdate,options
    );
  }
export const getPutTagsIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tags/${id}`,
    baseURL: '',


  });
}

/**
 * Delete a tag
 * @summary Delete tag
 */
export const deleteTagsId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.delete(
      `/tags/${id}`,options
    );
  }
export const getDeleteTagsIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tags/${id}`,
    baseURL: '',


  });
}

/**
 * Retrieve all tasks associated with a specific tag
 * @summary Get tasks by tag
 */
export const getTagsIdTasks = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TasksListResponse>> => {
    return axios.get(
      `/tags/${id}/tasks`,options
    );
  }
export const getGetTagsIdTasksUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tags/${id}/tasks`,
    baseURL: '',


  });
}

/**
 * Create a new subtask for a task
 * @summary Create subtask
 */
export const postTasksIdSubtasks = (
    id: number,
    subtaskCreate: SubtaskCreate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubtaskResponse>> => {
    return axios.post(
      `/tasks/${id}/subtasks`,
      subtaskCreate,options
    );
  }
export const getPostTasksIdSubtasksUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/subtasks`,
    baseURL: '',


  });
}

/**
 * Get all subtasks for a task
 * @summary Get task subtasks
 */
export const getTasksIdSubtasks = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubtasksResponse>> => {
    return axios.get(
      `/tasks/${id}/subtasks`,options
    );
  }
export const getGetTasksIdSubtasksUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/subtasks`,
    baseURL: '',


  });
}

/**
 * Retrieve a specific subtask
 * @summary Get subtask by ID
 */
export const getSubtasksId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubtaskResponse>> => {
    return axios.get(
      `/subtasks/${id}`,options
    );
  }
export const getGetSubtasksIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/subtasks/${id}`,
    baseURL: '',


  });
}

/**
 * Update an existing subtask
 * @summary Update subtask
 */
export const putSubtasksId = (
    id: number,
    subtaskUpdate: SubtaskUpdate, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubtaskResponse>> => {
    return axios.put(
      `/subtasks/${id}`,
      subtaskUpdate,options
    );
  }
export const getPutSubtasksIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/subtasks/${id}`,
    baseURL: '',


  });
}

/**
 * Delete a subtask
 * @summary Delete subtask
 */
export const deleteSubtasksId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SuccessResponse>> => {
    return axios.delete(
      `/subtasks/${id}`,options
    );
  }
export const getDeleteSubtasksIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/subtasks/${id}`,
    baseURL: '',


  });
}

/**
 * Toggle the completion status of a subtask
 * @summary Toggle subtask completion
 */
export const patchSubtasksIdToggle = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SubtaskResponse>> => {
    return axios.patch(
      `/subtasks/${id}/toggle`,
      undefined,options
    );
  }
export const getPatchSubtasksIdToggleUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/subtasks/${id}/toggle`,
    baseURL: '',


  });
}

/**
 * Retrieve activity logs for the authenticated user
 * @summary Get user activity logs
 */
export const getActivityLogs = (
    params?: GetActivityLogsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLogsResponse>> => {
    return axios.get(
      `/activity-logs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getGetActivityLogsUrl = (params?: GetActivityLogsParams,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/activity-logs`,
    baseURL: '',
    params,

  });
}

/**
 * Retrieve a specific activity log
 * @summary Get activity log by ID
 */
export const getActivityLogsId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLogResponse>> => {
    return axios.get(
      `/activity-logs/${id}`,options
    );
  }
export const getGetActivityLogsIdUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/activity-logs/${id}`,
    baseURL: '',


  });
}

/**
 * Retrieve activity logs for a specific task
 * @summary Get task activity logs
 */
export const getTasksIdActivityLogs = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ActivityLogsResponse>> => {
    return axios.get(
      `/tasks/${id}/activity-logs`,options
    );
  }
export const getGetTasksIdActivityLogsUrl = (id: number,) => {

  return axios.create({
    baseURL: '',
    params: null,
  }).getUri({
    url: `/tasks/${id}/activity-logs`,
    baseURL: '',


  });
}

export type GetHealthResult = AxiosResponse<string>
export type PostAuthRegisterResult = AxiosResponse<SuccessResponse>
export type PostAuthLoginResult = AxiosResponse<LoginResponse>
export type PostAuthLogoutResult = AxiosResponse<SuccessResponse>
export type GetAuthMeResult = AxiosResponse<UserResponse>
export type PutAuthTimezoneResult = AxiosResponse<UserResponse>
export type GetTasksResult = AxiosResponse<TasksListResponse>
export type PostTasksResult = AxiosResponse<TaskResponse>
export type GetTasksIdResult = AxiosResponse<TaskResponse>
export type PutTasksIdResult = AxiosResponse<TaskResponse>
export type DeleteTasksIdResult = AxiosResponse<SuccessResponse>
export type PatchTasksIdCompleteResult = AxiosResponse<SuccessResponse>
export type PatchTasksIdUncompleteResult = AxiosResponse<SuccessResponse>
export type PatchTasksIdRestoreResult = AxiosResponse<SuccessResponse>
export type GetTasksAnalyticsSummaryResult = AxiosResponse<AnalyticsResponse>
export type PostTasksBulkDeleteResult = AxiosResponse<SuccessResponse>
export type PostTasksBulkCompleteResult = AxiosResponse<SuccessResponse>
export type PostTasksIdTagsResult = AxiosResponse<SuccessResponse>
export type GetTasksIdTagsResult = AxiosResponse<TagsResponse>
export type DeleteTasksIdTagsTagIdResult = AxiosResponse<SuccessResponse>
export type GetCategoriesResult = AxiosResponse<CategoriesResponse>
export type PostCategoriesResult = AxiosResponse<CategoryResponse>
export type GetCategoriesIdResult = AxiosResponse<CategoryResponse>
export type PutCategoriesIdResult = AxiosResponse<CategoryResponse>
export type DeleteCategoriesIdResult = AxiosResponse<SuccessResponse>
export type GetTagsResult = AxiosResponse<TagsResponse>
export type PostTagsResult = AxiosResponse<TagResponse>
export type GetTagsIdResult = AxiosResponse<TagResponse>
export type PutTagsIdResult = AxiosResponse<TagResponse>
export type DeleteTagsIdResult = AxiosResponse<SuccessResponse>
export type GetTagsIdTasksResult = AxiosResponse<TasksListResponse>
export type PostTasksIdSubtasksResult = AxiosResponse<SubtaskResponse>
export type GetTasksIdSubtasksResult = AxiosResponse<SubtasksResponse>
export type GetSubtasksIdResult = AxiosResponse<SubtaskResponse>
export type PutSubtasksIdResult = AxiosResponse<SubtaskResponse>
export type DeleteSubtasksIdResult = AxiosResponse<SuccessResponse>
export type PatchSubtasksIdToggleResult = AxiosResponse<SubtaskResponse>
export type GetActivityLogsResult = AxiosResponse<ActivityLogsResponse>
export type GetActivityLogsIdResult = AxiosResponse<ActivityLogResponse>
export type GetTasksIdActivityLogsResult = AxiosResponse<ActivityLogsResponse>
